services:
  quickStreamdb:
    image: postgres:15
    container_name: quickStreamdb
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: quickStream
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quickStream
    volumes:
      - ./mydb:/var/lib/postgresql/data